# Generated by Django 3.2.11 on 2022-01-17 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorman', '0001_db_initialization'),
    ]

    operations = [
        migrations.RunSQL('''
        -- system-related data
        INSERT INTO "Role" (id_role, code, name)
        VALUES (1, 'participant', 'Participant');
        INSERT INTO "Role" (id_role, code, name)
        VALUES (2, 'tutor', 'Tutor');
        
        -- domain-related data
        INSERT INTO "SchoolType" (id_school_type, name)
        VALUES (1, 'Primary School');
        INSERT INTO "SchoolType" (id_school_type, name)
        VALUES (2, 'High School');
        INSERT INTO "SchoolType" (id_school_type, name)
        VALUES (3, 'Technical School');
        INSERT INTO "SchoolType" (id_school_type, name)
        VALUES (4, 'Vocational School');
        INSERT INTO "SchoolType" (id_school_type, name)
        VALUES (5, 'Special School');
        
        INSERT INTO "GradeLevel" (id_grade_level, id_school_type, grade_number)
        VALUES (1, 1, 1);
        INSERT INTO "GradeLevel" (id_grade_level, id_school_type, grade_number)
        VALUES (2, 1, 2);
        INSERT INTO "GradeLevel" (id_grade_level, id_school_type, grade_number)
        VALUES (3, 1, 3);
        INSERT INTO "GradeLevel" (id_grade_level, id_school_type, grade_number)
        VALUES (4, 1, 4);
        INSERT INTO "GradeLevel" (id_grade_level, id_school_type, grade_number)
        VALUES (5, 1, 5);
        INSERT INTO "GradeLevel" (id_grade_level, id_school_type, grade_number)
        VALUES (6, 1, 6);
        INSERT INTO "GradeLevel" (id_grade_level, id_school_type, grade_number)
        VALUES (7, 1, 7);
        INSERT INTO "GradeLevel" (id_grade_level, id_school_type, grade_number)
        VALUES (8, 1, 8);
        
        INSERT INTO "GradeLevel" (id_grade_level, id_school_type, grade_number)
        VALUES (9, 2, 1);
        INSERT INTO "GradeLevel" (id_grade_level, id_school_type, grade_number)
        VALUES (10, 2, 2);
        INSERT INTO "GradeLevel" (id_grade_level, id_school_type, grade_number)
        VALUES (11, 2, 3);
        INSERT INTO "GradeLevel" (id_grade_level, id_school_type, grade_number)
        VALUES (12, 2, 4);
        
        INSERT INTO "GradeLevel" (id_grade_level, id_school_type, grade_number)
        VALUES (13, 3, 1);
        INSERT INTO "GradeLevel" (id_grade_level, id_school_type, grade_number)
        VALUES (14, 3, 2);
        INSERT INTO "GradeLevel" (id_grade_level, id_school_type, grade_number)
        VALUES (15, 3, 3);
        INSERT INTO "GradeLevel" (id_grade_level, id_school_type, grade_number)
        VALUES (16, 3, 4);
        INSERT INTO "GradeLevel" (id_grade_level, id_school_type, grade_number)
        VALUES (17, 3, 5);
        
        INSERT INTO "GradeLevel" (id_grade_level, id_school_type, grade_number)
        VALUES (18, 4, 1);
        INSERT INTO "GradeLevel" (id_grade_level, id_school_type, grade_number)
        VALUES (19, 4, 2);
        INSERT INTO "GradeLevel" (id_grade_level, id_school_type, grade_number)
        VALUES (20, 4, 3);
        INSERT INTO "GradeLevel" (id_grade_level, id_school_type, grade_number)
        VALUES (21, 4, 4);
        INSERT INTO "GradeLevel" (id_grade_level, id_school_type, grade_number)
        VALUES (22, 4, 5);
        
        INSERT INTO "Subject" (id_subject, name)
        VALUES (1, 'Mathematics');
        INSERT INTO "Subject" (id_subject, name)
        VALUES (2, 'Physics');
        INSERT INTO "Subject" (id_subject, name)
        VALUES (3, 'Chemistry');
        
        INSERT INTO "Book" (id_book, name, author)
        VALUES (1, 'Matematyka 1', 'Nowsza Era');
        INSERT INTO "Book" (id_book, name, author)
        VALUES (2, 'Matematyka 2', 'Nowsza Era');
        INSERT INTO "Book" (id_book, name, author)
        VALUES (3, 'Matematyka 3', 'Nowsza Era');
        INSERT INTO "Book" (id_book, name, author)
        VALUES (4, 'Matematyka 4', 'Nowsza Era');
        
        INSERT INTO "Book" (id_book, name, author)
        VALUES (5, 'Fizyka 1', 'Nowsza Era');
        INSERT INTO "Book" (id_book, name, author)
        VALUES (6, 'Fizyka 2', 'Nowsza Era');
        INSERT INTO "Book" (id_book, name, author)
        VALUES (7, 'Fizyka 3', 'Nowsza Era');
        INSERT INTO "Book" (id_book, name, author)
        VALUES (8, 'Fizyka 4', 'Nowsza Era');
        
        INSERT INTO "Book" (id_book, name, author)
        VALUES (9, 'Chemia 1', 'Nowsza Era');
        INSERT INTO "Book" (id_book, name, author)
        VALUES (10, 'Chemia 2', 'Nowsza Era');
        INSERT INTO "Book" (id_book, name, author)
        VALUES (11, 'Chemia 3', 'Nowsza Era');
        INSERT INTO "Book" (id_book, name, author)
        VALUES (12, 'Chemia 4', 'Nowsza Era');
        
        INSERT INTO "SpecialNeed" (id_special_need, name)
        VALUES (1, 'Dyslexia');
        INSERT INTO "SpecialNeed" (id_special_need, name)
        VALUES (2, 'Dyscalculia');
        INSERT INTO "SpecialNeed" (id_special_need, name)
        VALUES (3, 'Dysgraphia');
        
        INSERT INTO "TutoringScope" (id_tutoring_scope, name)
        VALUES (1, 'Equalizing classes');
        INSERT INTO "TutoringScope" (id_tutoring_scope, name)
        VALUES (2, 'Olympiad preparation');
        INSERT INTO "TutoringScope" (id_tutoring_scope, name)
        VALUES (3, 'Along school program');
        INSERT INTO "TutoringScope" (id_tutoring_scope, name)
        VALUES (4, 'Ahead of school program');
        
        INSERT INTO "DiscountRule" (id_discount_rule, code, name)
        VALUES (1, 'ADJACENT_TO_FREE_SLOTS', 'Adjacent to free slots');
        INSERT INTO "DiscountRule" (id_discount_rule, code, name)
        VALUES (2, 'ALL_SLOTS', 'All free slots');
        
        INSERT INTO "WorkingMethod" (id_working_method, name, description)
        VALUES (1, 'Kahoutett quiz #1', 'example.com');
        INSERT INTO "WorkingMethod" (id_working_method, name, description)
        VALUES (2, 'Kahoutett quiz #2', 'example.com');
        ''')
    ]
