# Generated by Django 3.2.11 on 2022-01-17 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorman', '0002_db_domain_data'),
    ]

    operations = [
        migrations.RunSQL('''
            -- a teacher and her tutoring
            INSERT INTO "Contact" (id_contact, email, phone_number, parent_email, parent_phone_number, description)
            VALUES (1, 'teacher@tutors.com', '+48976925152', NULL, NULL, NULL);
            
            INSERT INTO "User" (id_user, id_role, id_grade_level, id_contact, first_name, last_name, date_of_birth)
            VALUES (1, 2, NULL, 1, 'Anna', 'Kowalsky', DATETIME('2000-11-10'));

            INSERT INTO "Description" (id_description, banner_url, description)
            VALUES (1, 'https://upload.wikimedia.org/wikipedia/en/a/a9/Example.jpg', 'Cool tutoring for everyone!');

            INSERT INTO "TimeslotHideRule" (id_timeslot_hide_rule, total_income_threshold, taken_slots_ratio_threshold)
            VALUES (1, NULL, 0.8);

            INSERT INTO "Tutoring" (id_tutoring, id_teacher, id_tutoring_scope, id_subject, id_book, id_description,
                                    id_timeslot_hide_rule, name, timeslot_mins, price_for_timeslot)
            VALUES (1, 1, 3, 1, 1, 1, 1, 'Math simply explained!', 60, 50);

            INSERT INTO "Medium" (id_medium, name, description, is_remote) VALUES (1, 'Discurd', 'Link to server: discurd.dg/invite/583621', 1);

            INSERT INTO "Timeslot" (id_timeslot, id_tutoring, id_medium, takes_place_at, allow_multiple_participants, timeslot_mins)
            VALUES (1, 1, 1, DATETIME('2021-11-06 10:00'), 0, 60);
            INSERT INTO "Timeslot" (id_timeslot, id_tutoring, id_medium, takes_place_at, allow_multiple_participants, timeslot_mins)
            VALUES (2, 1, 1, DATETIME('2021-11-06 11:00'), 0, 60);
            INSERT INTO "Timeslot" (id_timeslot, id_tutoring, id_medium, takes_place_at, allow_multiple_participants, timeslot_mins)
            VALUES (3, 1, 1, DATETIME('2021-11-06 12:00'), 0, 60);
            INSERT INTO "Timeslot" (id_timeslot, id_tutoring, id_medium, takes_place_at, allow_multiple_participants, timeslot_mins)
            VALUES (4, 1, 1, DATETIME('2021-11-07 11:00'), 1, 60);
            INSERT INTO "Timeslot" (id_timeslot, id_tutoring, id_medium, takes_place_at, allow_multiple_participants, timeslot_mins)
            VALUES (5, 1, 1, DATETIME('2021-11-07 12:00'), 0, 60);

            INSERT INTO "Discount" (id_discount, id_tutoring, id_discount_rule, new_price_multiplier,
                                    due_date, consumed_count, max_consumed_count)
            VALUES (1, 1, 1, 0.8, DATETIME('2021-12-31 23:59'), 0, NULL);

            INSERT INTO "PaymentMethod" (id_payment_method, name, description)
            VALUES (1, 'Bank transfer', 'Title: \"Math simply explained!\", account number: US57955545888137044630272802');

            INSERT INTO "Attribute" (id_attribute, name)
            VALUES (1, 'Logical thinking');
            INSERT INTO "Attribute" (id_attribute, name)
            VALUES (2, 'Understanding story-based tasks');

            -- a student that joined the above tutoring
            INSERT INTO "Contact" (id_contact, email, phone_number, parent_email, parent_phone_number, description)
            VALUES (2, 'jack@black.com', '+48976925152', 'vitaly@black.com', '+485729638145', NULL);

            INSERT INTO "User" (id_user, id_role, id_grade_level, id_contact, first_name, last_name, date_of_birth)
            VALUES (2, 2, 6, 2, 'Jack', 'Black', DATETIME('2008-05-01'));

            -- another student
            INSERT INTO "Contact" (id_contact, email, phone_number, parent_email, parent_phone_number, description)
            VALUES (3, 'anne@white.com', '+48526221631', 'zenon@white.com', '+48863196312',
                    'has problems with calculating percentages');

            INSERT INTO "User" (id_user, id_role, id_grade_level, id_contact, first_name, last_name, date_of_birth)
            VALUES (3, 2, 5, 3, 'Anne', 'White', DATETIME('2006-02-12'));

            INSERT INTO "User_SpecialNeed" (id_user_special_need, id_user, id_special_need)
            VALUES (1, 2, 1);

            INSERT INTO "TutoringParticipant" (id_tutoring_participant, id_user)
            VALUES (1, 2);

            INSERT INTO "TutoringParticipant" (id_tutoring_participant, id_user)
            VALUES (2, 3);

            INSERT INTO "Bill" (id_bill, id_payment_method, billed_at, price, payment_confirmed)
            VALUES (1, 1, DATETIME('2021-11-02 15:22:18'), 50, 1);
            INSERT INTO "Bill" (id_bill, id_payment_method, billed_at, price, payment_confirmed)
            VALUES (2, 1, DATETIME('2021-11-02 16:12:17'), 50, 1);

            INSERT INTO "Bill" (id_bill, id_payment_method, billed_at, price, payment_confirmed)
            VALUES (3, 1, DATETIME('2021-12-12 12:45:22'), 50, 1);
            INSERT INTO "Bill" (id_bill, id_payment_method, billed_at, price, payment_confirmed)
            VALUES (4, 1, DATETIME('2021-11-12 12:52:31'), 50, 1);

            INSERT INTO "Timeslot_TutoringParticipant" (id_timeslot_tutoring_participant, id_timeslot,
                                                        id_tutoring_participant, id_bill)
            VALUES (1, 3, 1, 1);
            INSERT INTO "Timeslot_TutoringParticipant" (id_timeslot_tutoring_participant, id_timeslot,
                                                        id_tutoring_participant, id_bill)
            VALUES (2, 5, 1, 2);

            INSERT INTO "Timeslot_TutoringParticipant" (id_timeslot_tutoring_participant, id_timeslot,
                                                        id_tutoring_participant, id_bill)
            VALUES (3, 4, 2, 3);
            INSERT INTO "Timeslot_TutoringParticipant" (id_timeslot_tutoring_participant, id_timeslot,
                                                        id_tutoring_participant, id_bill)
            VALUES (4, 4, 2, 4);

            INSERT INTO "TutoringParticipant_WorkingMethod" (id_tutoring_participant_working_method, id_tutoring_participant,
                                                             id_working_method, completed)
            VALUES (1, 1, 1, 1);
            INSERT INTO "TutoringParticipant_WorkingMethod" (id_tutoring_participant_working_method, id_tutoring_participant,
                                                             id_working_method, completed)
            VALUES (2, 1, 2, 0);

            INSERT INTO "TeachingNote" (id_teaching_note, id_tutoring_participant, note)
            VALUES (1, 1, 'Knows how to use a graphical calculator!');
            INSERT INTO "TeachingNote" (id_teaching_note, id_tutoring_participant, note)
            VALUES (2, 1, 'Likes trains');

            INSERT INTO "TutoringParticipant_Attribute" (id_tutoring_participant_attribute, id_tutoring_participant,
                                                         id_attribute, value)
            VALUES (1, 1, 1, '9');
            INSERT INTO "TutoringParticipant_Attribute" (id_tutoring_participant_attribute, id_tutoring_participant,
                                                         id_attribute, value)
            VALUES (2, 1, 1, '7');

            INSERT INTO "Rating" (id_rating, id_tutoring, rate, comment)
            VALUES (1, 1, 10, 'Best teacher I have ever had!');

            INSERT INTO "RatingDispute" (id_rating_dispute, id_rating, reason, is_reviewed)
            VALUES (1, 1, 'Great to hear! :)', 1);

            INSERT INTO "Cancellation" (id_cancellation, id_timeslot_tutoring_participant, approved)
            VALUES (1, 2, 1);
        ''')
    ]
